// <auto-generated />
using System;
using CheckPoint21114.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CheckPoint21114.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20191116173801_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("CheckPoint21114.Core.Models.Assignment", b =>
                {
                    b.Property<int>("ChoreId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChoreTypeId")
                        .HasColumnType("INTEGER");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("CheckPoint21114.Core.Models.Chore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssignmentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Chores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignmentId = 0,
                            Deadline = new DateTime(2019, 11, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Wipe dust off of tables",
                            Title = "Dusting"
                        },
                        new
                        {
                            Id = 2,
                            AssignmentId = 0,
                            Deadline = new DateTime(2019, 11, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = " Collect all garbage and take to dump",
                            Title = "Take out Garbage"
                        });
                });

            modelBuilder.Entity("CheckPoint21114.Core.Models.ChoreType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ChoreTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Inside Chore"
                        },
                        new
                        {
                            Id = 2,
                            Title = "OutsideChore"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
